<p style="align: center;"><img src="https://static.tildacdn.com/tild6636-3531-4239-b465-376364646465/Deep_Learning_School.png", width=300, height=300></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>

---

<h2 style="text-align: center;"><b>PyTorch. Основы: синтаксис, torch.cuda и torch.autograd</b></h2>

<p style="align: center;"><img src="https://raw.githubusercontent.com/pytorch/pytorch/master/docs/source/_static/img/pytorch-logo-dark.png", width=400, height=300></p>

На этом занятии мы рассмотрим основы фреймворка глубокого обучения PyTorch.  

Когда хочется написать какую-нибудь нейросеть, решающую определённую задачу, будь то какая-нибудь простая классификация чего-либо или обнаружение лиц людей на видео. Всё, конечно, всегда начинается со **сбора данных**, а уже потом реализуются модели и проводятся эксперименты.  

Однако люди быстро поняли, что писать свои нейронные сети каждый раз с нуля ну очень уж долго и неразумно, поэтому придумали так называемые **фреймворки** - модули, в которых есть функционал, с помощью которого можно быстро и просто решать типовые задачи, и уже с помощью этих средств писать решения к более сложным задачам.

Есть много различных фремворков глубокого обучения. Разница между ними прежде всего в том, каков общий принцип вычислений. 
Например, в **Caffe и Caffe2** вы пишете код, по сути, составляя его из готовых "кусочков", как в Lego, в **TensorFlow и Theano** вы сначала объявляете вычислительный граф, потом компилируете его и запускаете (sees.run()), в то время как в **Torch и PyTorch** вы пишете почти точно так же, как на NumPy, а граф вычислений создаётся только при запуске (то есть существует только во время выполнения, потом он "разрушается"). **Keras** позволяет как строить блоки, так и компилировать свой граф:

<p style="align: center;"><img src="https://habrastorage.org/web/e3e/c3e/b78/e3ec3eb78d714a7993a6b922911c0866.png", width=500, height=500></p>  
<p style="text-align: center;"><i>Картинка взята из отличной [статьи на Хабре](https://habr.com/post/334380/)</i><p>

<h3 style="text-align: center;"><b>Установка</b></h3>

Инструкция по установке PyTorch есть на официальном [Github'e Deep Learning School](https://github.com/deepmipt/dlschl/wiki/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F-%D0%BF%D0%BE-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B5-PyTorch).

<h3 style="text-align: center;">Синтаксис<b></b></h3>

In [32]:
import torch

Сначала немного фактов про PyTorch:  
- динамический граф вычислений
- удобные модули `torch.nn` и `torchvision для` написания нейросеток с минимальными усилиями
- в некоторых задачах даже быстрее TensorFlow (но не во всех)  
- легко проводить вычисления на GPU

Если PyTorch представить формулой, то она будет такой:  

$$PyTorch = NumPy + CUDA + Autograd$$

(CUDA - [wiki](https://ru.wikipedia.org/wiki/CUDA))

Посмотрим, как в PyTorch выполняются операции с векторами.  

Напоминание: **тензором** называется многомерный вектор, то есть есть:  

x = np.array([1,2,3]) - вектор = тензор размерности 1 (то есть (1,))  
y = np.array([[1, 2, 3], [4, 5, 6]]) - матрица = тензор размерности 2 (в данном случае тензор (2, 3))  
z = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],  
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],  
              [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]) - "кубик" (3, 3, 3) = тензор размерности 3 (в данном случае (3, 3, 3))

Простейшим примером 3-мерного тензора является **картинка** - это "параллелепипед" из чисел, у коготорого три размерности - высота, ширина и количество каналов, значит это тензор размерности 3.

Понятие тензора нужно знать потому, что в PyTorch мы оперируем переменными типа `torch.Tensor` (`FloatTensor`, `IntTensor`, `ByteTensor`), и пугаться их названий совершенно не нужно - это просто векторы, у которых несколько размерностей.

Все типы тензоров:

In [33]:
torch.HalfTensor      # 16 бит, с плавающей точкой
torch.FloatTensor     # 32 бита,  с плавающей точкой
torch.DoubleTensor    # 64 бита, с плавающей точкой

torch.ShortTensor     # 16 бит, целочисленный, знаковый
torch.IntTensor       # 32 бита, целочисленный, знаковый
torch.LongTensor      # 64 бита, целочисленный, знаковый

torch.CharTensor      # 8 бит, целочисленный, знаковый
torch.ByteTensor      # 8 бит, целочисленный, беззнаковый

torch.ByteTensor

Мы будем использовать только `torch.FloatTensor()` и `torch.IntTensor()`. 

Перейдём к делу:

* Создание тензоров:

In [34]:
a = torch.FloatTensor([1, 2])
a

tensor([ 1.,  2.])

In [35]:
a.shape

torch.Size([2])

In [36]:
b = torch.FloatTensor([[1,2,3], [4,5,6]])
b

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])

In [37]:
b.shape

torch.Size([2, 3])

In [38]:
x = torch.FloatTensor(2,3,4)

In [39]:
x

RuntimeError: Overflow when unpacking long

In [40]:
x = torch.FloatTensor(100)
x

RuntimeError: Overflow when unpacking long

In [41]:
x = torch.IntTensor(45, 57, 14, 2)
x.shape

torch.Size([45, 57, 14, 2])

**Обратите внимание** - если вы создаёте тензор через задание размерностей (как в примере выше), то он изначально заполняюстя случайным "мусором". Что инициализировать нулями, нужно написать .zero_() в конце:

In [42]:
x = torch.IntTensor(3, 2, 4)
x

tensor([[[-4.4551e+08,  3.2566e+04, -4.4551e+08,  3.2566e+04],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]], dtype=torch.int32)

In [43]:
x = torch.IntTensor(3, 2, 4).zero_()
x

tensor([[[ 0,  0,  0,  0],
         [ 0,  0,  0,  0]],

        [[ 0,  0,  0,  0],
         [ 0,  0,  0,  0]],

        [[ 0,  0,  0,  0],
         [ 0,  0,  0,  0]]], dtype=torch.int32)

Аналог функции `np.reshape()` == `torch.view()`:

In [44]:
b.view(3, 2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]])

In [45]:
b

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])

**Обратите внимание** - torch.view() создаёт новый тензор, а не изменяет старый!

In [46]:
b.view(-1)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.])

In [47]:
b

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])

* Изменение типа тензора:

In [48]:
a = torch.FloatTensor([1.5, 3.2, -7])

In [49]:
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [50]:
a.type_as(torch.ByteTensor())

tensor([   1,    3,  249], dtype=torch.uint8)

Обратите внимание, что при `.type_as()` создаётся новый тензор (старый не меняется), то есть это не in-place операция:

In [51]:
a

tensor([ 1.5000,  3.2000, -7.0000])

* Индексация точная такая же, как и в NumPy:

In [52]:
a = torch.FloatTensor([[100, 20, 35], [15, 163, 534], [52, 90, 66]])
a

tensor([[ 100.,   20.,   35.],
        [  15.,  163.,  534.],
        [  52.,   90.,   66.]])

In [53]:
a[0, 0]

tensor(100.)

In [54]:
a[0][0]

tensor(100.)

In [55]:
a[0:2, 0:2]

tensor([[ 100.,   20.],
        [  15.,  163.]])

### Задача 1

1). Создайте два вещественных тензора: `a` размером (3, 4) и `b` размером (12,)   
2). Создайте тензор `c`, являющийся тензором `b`, но размера (2, 2, 3)  
3). Выведите первый столбец матрицы `a` с помощью индексации

In [56]:
# Ваш код здесь

**Арифметика и булевы операции** работаю также, как и в NumPy, **НО** лучше использовать не опреаторы `+`, `-`, `*`, `/`, а их аналоги:  

| Оператор | Аналог |
|:-:|:-:|
|`+`| `torch.add()` |
|`-`| `torch.sub()` |
|`*`| `torch.mul()` |
|`/`| `torch.div()` |

* Сложение:

In [57]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [58]:
a + b

tensor([[   0.,    0.,    0.],
        [   0.,    0.,    0.],
        [ 200.,  400.,  600.]])

Лучше:

In [59]:
a.add(b)

tensor([[   0.,    0.,    0.],
        [   0.,    0.,    0.],
        [ 200.,  400.,  600.]])

In [60]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [61]:
a + b

tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])

* Вычитание:

In [62]:
a - b

tensor([[   2.,    4.,    6.],
        [  20.,   40.,   60.],
        [ 200.,  400.,  600.]])

Лучше:

In [63]:
a.sub(b)

tensor([[   2.,    4.,    6.],
        [  20.,   40.,   60.],
        [ 200.,  400.,  600.]])

* Умножение (поэлементное):

In [64]:
a * b

tensor([[    -1.,     -4.,     -9.],
        [  -100.,   -400.,   -900.],
        [-10000., -40000., -90000.]])

Лучше:

In [65]:
a.mul(b)

tensor([[    -1.,     -4.,     -9.],
        [  -100.,   -400.,   -900.],
        [-10000., -40000., -90000.]])

* Деление (поэлементное):

In [66]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [67]:
a / b

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

Лучше:

In [68]:
a.div(b)

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

Заметьте, все эти операции **не меняют исходные тензоры**, а **создают новые**:

In [69]:
a

tensor([[   1.,    2.,    3.],
        [  10.,   20.,   30.],
        [ 100.,  200.,  300.]])

In [70]:
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [ 100.,  200.,  300.]])

### Задача 2

1). Создайте два вещественных тензора: `a` размером (5, 2) и `b` размером (1,10)   
2). Создайте тензор `c`, являющийся тензором `b`, но размера (5, 2)  
3). Произведите все арифметические операции с тензорами `a` и `c`

In [71]:
# Ваш код здесь

* **Операторы сравнения**:

In [72]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [73]:
a == b

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 1,  1,  1]], dtype=torch.uint8)

In [74]:
a != b

tensor([[ 1,  1,  1],
        [ 1,  1,  1],
        [ 0,  0,  0]], dtype=torch.uint8)

In [75]:
a < b

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]], dtype=torch.uint8)

In [76]:
a > b

tensor([[ 1,  1,  1],
        [ 1,  1,  1],
        [ 0,  0,  0]], dtype=torch.uint8)

* **Булевы маски**:

In [77]:
a[a > b]

tensor([  1.,   2.,   3.,  10.,  20.,  30.])

In [78]:
b[a == b]

tensor([ 100.,  200.,  300.])

Опять же, тензоры не меняются:

In [79]:
a

tensor([[   1.,    2.,    3.],
        [  10.,   20.,   30.],
        [ 100.,  200.,  300.]])

In [80]:
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [ 100.,  200.,  300.]])

Применение **стандартных функций** такое же, как и в numpy - поэлементное:

In [81]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])

In [82]:
a.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [83]:
torch.sin(a)

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [84]:
a.cos()

tensor([[ 0.5403, -0.4161, -0.9900],
        [-0.8391,  0.4081,  0.1543],
        [ 0.8623,  0.4872, -0.0221]])

In [85]:
a.exp()

tensor([[ 2.7183e+00,  7.3891e+00,  2.0086e+01],
        [ 2.2026e+04,  4.8517e+08,  1.0686e+13],
        [        inf,         inf,         inf]])

In [86]:
a.log()

tensor([[ 0.0000,  0.6931,  1.0986],
        [ 2.3026,  2.9957,  3.4012],
        [ 4.6052,  5.2983,  5.7038]])

In [87]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [88]:
b.abs()

tensor([[   1.,    2.,    3.],
        [  10.,   20.,   30.],
        [ 100.,  200.,  300.]])

**Сумма, среднее, максимум, минимум**:

In [89]:
a.sum()

tensor(666.)

In [90]:
a.mean()

tensor(74.)

По осям:

In [91]:
a.sum(0)

tensor([ 111.,  222.,  333.])

In [92]:
a.sum(1)

tensor([   6.,   60.,  600.])

In [93]:
a.max()

tensor(300.)

In [94]:
a.max(0)

(tensor([ 100.,  200.,  300.]), tensor([ 2,  2,  2]))

In [95]:
a.min()

tensor(1.)

In [96]:
a.min(0)

(tensor([ 1.,  2.,  3.]), tensor([ 0,  0,  0]))

Обратите внимание - второй тензор при вызове функций .max() и .min() - это индексы этих максимальных/минимальных элементов по указанной размерности (то есть в данном случае a.min() вернул (1, 2, 3) - минимумы по 0 оси (по столбцам), и их индексы по 0-ой оси (0,0,0) (номер каждого элемента в своём столбце)).

### Задача 3

Создайте тензор `a` размерности (100, 780, 780, 3) (можно интерпретировать это как 100 картинок размера 780х780 с тремя цветовыми каналами) и выведите первый элемент этого тензора как картинку (с помощью matplotlib.pyplot).

Выведите среднее элементов по 1-ой оси (по сути - средняя картинка по всем картинкам) и по 4-ой оси (по сути - усреднение каналов для каждой картинки).

In [97]:
# Ваш код здесь

**Матричные операции:**

In [98]:
z = x.mm(y)
z = torch.mm(x, y)
Матричное умножение.
z = x.mv(v)
z = torch.mv(x, v)
Умножение матрицы на вектор.
z = x.dot(y)
z = torch.dot(x, y)
Скалярное умножение тензоров.
bz = bx.bmm(by)
bz = torch.bmm(bx, by)
Перемножает матрицы целыми батчами.

SyntaxError: invalid syntax (<ipython-input-98-ec147a34bf39>, line 3)

* Транспонирование матрицы (тензора):

In [99]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
a

tensor([[   1.,    2.,    3.],
        [  10.,   20.,   30.],
        [ 100.,  200.,  300.]])

In [100]:
a.t()

tensor([[   1.,   10.,  100.],
        [   2.,   20.,  200.],
        [   3.,   30.,  300.]])

И снова - сам тензор не меняется (то есть при вызове создаётся новый):

In [101]:
a

tensor([[   1.,    2.,    3.],
        [  10.,   20.,   30.],
        [ 100.,  200.,  300.]])

* Скалярное произведение векторов (1-мерных тензоров):

In [102]:
a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])

In [103]:
a.dot(b)

tensor(-141.)

In [104]:
a @ b

tensor(-141.)

In [105]:
type(a)

torch.Tensor

In [106]:
type(b)

torch.Tensor

In [107]:
type(a @ b)

torch.Tensor

* Матричное умножение:

In [108]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [109]:
a.mm(b)

tensor([[   279.,    558.,    837.],
        [  2790.,   5580.,   8370.],
        [ 27900.,  55800.,  83700.]])

In [110]:
a @ b

tensor([[   279.,    558.,    837.],
        [  2790.,   5580.,   8370.],
        [ 27900.,  55800.,  83700.]])

Тензоры неизменны:

In [111]:
a

tensor([[   1.,    2.,    3.],
        [  10.,   20.,   30.],
        [ 100.,  200.,  300.]])

In [112]:
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [ 100.,  200.,  300.]])

In [113]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1], [-10], [100]])

In [114]:
print(a.shape, b.shape)

torch.Size([3, 3]) torch.Size([3, 1])


In [115]:
a @ b

tensor([[   279.],
        [  2790.],
        [ 27900.]])

Если "развернуть" тензор b просто в массив элементов (`torch.view(-1)`), умножение будет как на столбец:

In [116]:
b

tensor([[  -1.],
        [ -10.],
        [ 100.]])

In [117]:
b.view(-1)

tensor([  -1.,  -10.,  100.])

In [118]:
a @ b.view(-1)

tensor([   279.,   2790.,  27900.])

In [119]:
a.mv(b.view(-1))

tensor([   279.,   2790.,  27900.])

**Перевод из NumPy в PyTorch**:

In [120]:
import numpy as np

a = np.random.rand(3, 3)
a

array([[ 0.82995416,  0.75588695,  0.12408025],
       [ 0.6270365 ,  0.81527584,  0.72772993],
       [ 0.46361687,  0.52305469,  0.35805418]])

In [121]:
b = torch.from_numpy(a)
b

tensor([[ 0.8300,  0.7559,  0.1241],
        [ 0.6270,  0.8153,  0.7277],
        [ 0.4636,  0.5231,  0.3581]], dtype=torch.float64)

**НО!** Обратите внимание - a и b в этом случае будут использовать одно и то же хранилище данных, то есть измение одного тензора будет менять и другой:

In [122]:
b -= b
b

tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]], dtype=torch.float64)

In [123]:
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

**Перевод из PyTorch в NumPy:**

In [124]:
a = torch.FloatTensor(2, 3, 4)

In [125]:
print(a)

RuntimeError: Overflow when unpacking long

In [126]:
type(a)

torch.Tensor

In [127]:
x = a.numpy()
x

array([[[ -7.14397362e+22,   4.56346858e-41,  -7.14397362e+22,
           4.56346858e-41],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00]],

       [[  8.96831017e-44,   0.00000000e+00,   1.56945428e-43,
           0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
           0.00000000e+00]]], dtype=float32)

In [ ]:
x.shape

In [ ]:
type(x)

### Задача 4

Напишите функцию `forward_pass(X, w)` ($w_0$ входит в $w$) для одного нейрона (с сигмоидой) с помощью PyTorch (у вас уже должен быть код на NumPy).

In [128]:
def forward_pass(X, w):
    # Ваш код здесь

SyntaxError: unexpected EOF while parsing (<ipython-input-128-4d080ae46f66>, line 2)

In [ ]:
X = torch.FloatTensor([[-5, 5], [2, 3], [1, -1]])
w = torch.FloatTensor([[-0.5], [2.5]])
result = forward_pass(X, w)
print('result: {}'.format(result))

Должно получиться: 

|variable|value|
|-|-|
|**X**|torch.FloatTensor([[-5, 5], [15, 20], [100, -700]])|
|**w**|torch.FloatTensor([[-0.5], [150]])|
|**result**|torch.FloatTensor([[1.0000], [0.9985], [0.0474]])|   

<h3 style="text-align: center;">[CUDA](https://ru.wikipedia.org/wiki/CUDA)<b></b></h3>

[Краткое видео про то, как GPU используется в обучении нейросетей](https://www.youtube.com/watch?v=EobhK0UZm80)

Все вычисления в PyTorch можно проводить как на CPU, так и на GPU (Graphical Processing Unit) (если она у вас есть). В PyTorch переключение между ними делается очень просто, что является одной из ключевых его особенностей.

In [129]:
x = torch.FloatTensor(1024, 1024).uniform_()
x

tensor([[ 7.9731e-01,  4.6601e-01,  8.6153e-01,  ...,  2.5323e-01,
          9.3823e-01,  1.3455e-01],
        [ 2.3913e-01,  2.6659e-02,  9.7426e-01,  ...,  6.4511e-01,
          7.0774e-01,  6.7771e-01],
        [ 7.1618e-01,  3.3269e-01,  6.8090e-01,  ...,  6.3792e-01,
          1.9157e-01,  3.6917e-01],
        ...,
        [ 2.8950e-01,  1.8528e-01,  9.9694e-01,  ...,  4.4681e-01,
          9.5263e-02,  9.4072e-01],
        [ 2.3887e-01,  1.8414e-01,  7.6068e-01,  ...,  1.1467e-01,
          4.4128e-01,  8.0135e-02],
        [ 4.1611e-01,  7.8844e-02,  9.6175e-01,  ...,  5.4751e-01,
          1.1966e-02,  9.1312e-01]])

In [ ]:
x.is_cuda

Переместим на GPU:

In [ ]:
x = x.cuda()

In [ ]:
x.is_cuda

In [ ]:
x

Перемножим две тензора на GPu и вернём результат вычисления на CPU:

In [ ]:
a = torch.FloatTensor(10000, 10000).uniform_()
b = torch.FloatTensor(10000, 10000).uniform_()
c = a.cuda().mul(b.cuda()).cpu()

In [ ]:
c

In [ ]:
a

Тензоры, лежащие на CPU, и тензоры, лежащие на GPU, недоступны друг для друга:

In [ ]:
a = torch.FloatTensor(1000, 1000).uniform_().cpu()
b = torch.FloatTensor(10000, 10000).uniform_().cuda()

In [ ]:
a + b

Вот ещё немного про то, как можно работать с GPU:

In [ ]:
x = torch.FloatTensor(5, 5, 5).uniform_()

# проверяем, есть ли CUDA (то есть NVidia GPU)
if torch.cuda.is_available():
    # так можно получить имя устройства, которое связано с CUDA
    # (полезно в случае с несколькими видеокартами)
    device = torch.device('cuda')          # CUDA-device объект
    y = torch.ones_like(x, device=device)  # создаём тензор на GPU
    x = x.to(device)                       # тут можно просто ``.to("cuda")``
    z = x + y
    print(z)
    # с помощью``.to`` можно и изменить тип при перемещении
    print(z.to("cpu", torch.double))

<h3 style="text-align: center;">Autograd<b></b></h3>

Расшифровывается как Automatic Gradients (автоматическое взятие градиентов) - собственно, из названия понятно, что это модуль PyTorch, отвечающий за взятие производных.  

Возможно, для вас это бдет шок, но PyTorch (и любой фреймворк глубокого обучения) может продифференцировать функцию практически любой сложности.

Импортируем нужный класс:

In [ ]:
from torch.autograd import Variable

Идея такая: оборачиваем тензор в класс Variable(), получаем тоже тензор, но он имеет способность вычислять себе градиенты.  

Если а - тензор, обёрнутый в Variable(), то при вызове a.backward() берутся градиенты по всем переменным, от которых зависит тензор a.

**ВНИМАНИЕ!**  

Если вы используете версию `pytorch 0.4.0` или более новую, то ***`torch.Tensor` и `torch.Variable` - одно и то же!*** То есть Вам больше не нужно оборачивать в `Variable()`, чтобы брать градиенты - они берутся и по `Tensor()` (`torch.Variable()` - deprecated).

Примеры:

In [ ]:
x = torch.FloatTensor(3, 1).uniform_()
w = torch.FloatTensor(3, 3).uniform_() 
b = torch.FloatTensor(3, 1).uniform_()

x = Variable(x, requires_grad=True)
w = Variable(w, requires_grad=True)
b = Variable(b, requires_grad=False)

y = (w @ x).add_(b)

loss = y.sum()

# берём градиенты по всем "листьям" - в данном случае это тензоры x, w и b
loss.backward()

In [ ]:
x.grad

In [ ]:
w.grad

In [ ]:
b.grad

In [ ]:
y.grad

**Обратите внимание** - градиенты лежат в поле `.grad` у тех тензоров (Variable'ов), по которым брали эти градиенты. Градиенты **не лежат** в той Variable, от котороый они брались!

Получить тензор из `Variable()` можно с помощью поля `.data`:

In [ ]:
x

In [ ]:
x.data

### Задача 5

- Объявите тензор `a` размера (2, 3, 4) и тензор `b` размера (1, 8, 3), иницилизируйте их случайно равномерно (`.uniform_()`, как в примере выше)
- Создайте их копии на GPU, выведите их сумму и разность
- Затем измените форму тензора `b`, чтобы она совпадала с формой тензора `a`, получите тензор `c`  
- Переместите `c` на CPU, переместите `a` на CPU  
- Оберните их в `Variable()`
- Объявите тензор `L = torch.mean((c - a) `**` 2)` и посчитайте градиент `L` по `c` ( то есть $\frac{\partial{L}}{\partial{c}})$
- Получите тензор из `c` (то есть сейчас `c` - объект типа `Variable()`, вам нужно получить из него `FloatTensor()`)

In [ ]:
# Ваш код здесь

<h3 style="text-align: center;">Полезные ссылки:<b></b></h3>

*1). Мегаполезная статья по PyTorch (на русском), на её основе делался этот ноутбук: https://habr.com/post/334380/*

*2). Туториалы от самих разработчиков фреймворка: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py*

*3). Статья на arXiv о сравнении фреймворков глубокого обучения: https://arxiv.org/pdf/1511.06435.pdf*

4). *Ещё туториалы: https://github.com/yunjey/pytorch-tutorial*

*5). Сайт Facebook AI Research - отдела, который разрабатывает PyTorch и другие крутые вещи в AI: https://facebook.ai/developers/tools*