<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=600 height=500/></p>

<h3 style="text-align: center;"><b>Школа глубокого обучения ФПМИ МФТИ. Осень 2021</b></h3>

<h1 style="text-align: center;"><b>Библиотека NumPy</b></h1>

***Мы могли писать такой код и ни о чем не задумываться.***

In [ ]:
%%time
arr = []
n = 10**7
for i in range(n):
    arr.append(i*5)

CPU times: user 1.44 s, sys: 213 ms, total: 1.65 s
Wall time: 1.67 s


***Или такой...***

In [ ]:
%%time
def summ(a):
    ans = 0
    for i in a:
        ans += i
    return ans

arr = range(10**7)

print(summ(arr))

49999995000000
CPU times: user 680 ms, sys: 17.7 ms, total: 697 ms
Wall time: 700 ms


# Библиотека Numpy.
- ***``Numpy`` - это библиотека Python для вычислительно эффективных операций с многомерными массивами, предназначенная в основном для научных вычислений.***


- ***Пакет ``Numpy`` предоставляет $n$-мерные однородные массивы (все элементы одного типа) в них нельзя вставить или удалить элемент в произвольном месте. В ``Numpy`` реализовано много операций над массивами в целом.***

In [ ]:
!which python

/usr/local/bin/python


In [ ]:
# !conda install numpy
# !pip3 install numpy

In [ ]:
import numpy as np

## 1. Одномерные массивы

In [ ]:
a = [1, 2, 3]
b = np.array(a, dtype='float64')
print(type(b), type(a))

<class 'numpy.ndarray'> <class 'list'>


***Если типы разные, то идет неявный каст к одному.***

In [ ]:
a = [1, 2, 'a']
b = np.array(a)
print("Для list:", type(a[0]),
      "\nДля np.array:", type(b[0]))

Для list: <class 'int'> 
Для np.array: <class 'numpy.str_'>


In [ ]:
d = np.array([1, 2, 3])
d

array([1, 2, 3])

In [ ]:
type(d)

numpy.ndarray

***Можем посмотреть на все методы класса ``ndarray``.***

In [ ]:
set(dir(b)) - set(dir(object))

{'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delitem__',
 '__divmod__',
 '__float__',
 '__floordiv__',
 '__getitem__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__len__',
 '__lshift__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__neg__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setitem__',
 '__setstate__',
 '__sub__',


***Например узнаем размер массива.***

In [ ]:
arr = np.array([5, 6, 2, 1, 10], dtype='int32')

In [ ]:
arr.nbytes

20

***Если вы не знаете нужной функции, но понимаете, чего хотите, тогда можно воспользоваться поиском в документации.***

In [ ]:
np.lookfor('mean value of array') 

Search results for 'mean value of array'
----------------------------------------
numpy.ma.mean
    Returns the average of the array elements along given axis.
numpy.mean
    Compute the arithmetic mean along the specified axis.
numpy.nanmean
    Compute the arithmetic mean along the specified axis, ignoring NaNs.
numpy.put
    Replaces specified elements of an array with given values.
numpy.full
    Return a new array of given shape and type, filled with `fill_value`.
numpy.digitize
    Return the indices of the bins to which each value in input array belongs.
numpy.unpackbits
    Unpacks elements of a uint8 array into a binary-valued output array.
numpy.nanquantile
    Compute the qth quantile of the data along the specified axis,
numpy.ma.dot
    Return the dot product of two arrays.
numpy.count_nonzero
    Counts the number of non-zero values in the array ``a``.
numpy.ma.fix_invalid
    Return input with invalid data masked and replaced by a fill value.
numpy.matrix.partition
    R

***Далее можно почитать документацию про контретную функцию.***

In [ ]:
?np.ma.mean

In [ ]:
np.con*?

***Посмотрим на количественные характеристики ``ndarray``.***

In [ ]:
arr = np.array([[[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]], 
                [[1, 2, 3, 4],
                [2, 3, 4, 3],
                [1, 1, 1, 1]]])
print(arr)

[[[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]

 [[1 2 3 4]
  [2 3 4 3]
  [1 1 1 1]]]


In [ ]:
print("len:", len(arr), "-- количество элементов по первой оси.",
      "\nsize:", arr.size, "-- всего элементов в матрице.",
      "\nndim:", arr.ndim, "-- размерность матрицы.",
      "\nshape:", arr.shape, "-- количество элементов по каждой оси.")

len: 2 -- количество элементов по первой оси. 
size: 24 -- всего элементов в матрице. 
ndim: 3 -- размерность матрицы. 
shape: (2, 3, 4) -- количество элементов по каждой оси.


***Индексы.***

In [ ]:
a = np.array([1, 2, 3, 4])
a[0], a[1]

(1, 2)

***Последний элемент.***

In [ ]:
a[-1]

4

***Можем изменять объекты массива.***

In [ ]:
a[2] = -1
a

array([ 1,  2, -1,  4])

***``ndarray`` можно использовать в циклах. Но при этом теряется главное преимущество `Numpy` -- быстродействие. Всегда, когда это возможно, лучше использовать операции над массивами как едиными целыми.***

In [ ]:
for i in a:
    print(i)

1
2
-1
4


**Задача 1:** Создать numpy-массив, состоящий из первых четырех простых чисел, выведите его тип и размер:

In [ ]:
# решение

arr = np.array([2, 3, 5, 7])
print(arr)
print(arr.dtype)
print(type(arr))
print(arr.shape)
print(arr.nbytes)

[2 3 5 7]
int64
<class 'numpy.ndarray'>
(4,)
32


## Создание массивов.

In [ ]:
a = np.zeros(7) # массив из нулей
b = np.ones(7, dtype=np.int16) # массив из единиц
print(a)
print(b)

[0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1]


***Часто нужно создать нулевой массив такой же как другой.***

In [ ]:
c = np.zeros(7)
c

array([0., 0., 0., 0., 0., 0., 0.])

In [ ]:
c = np.zeros_like(b)
c

array([0, 0, 0, 0, 0, 0, 0], dtype=int16)

***Функция `np.arange` подобна `range`. Аргументы могут быть с плавающей точкой. Следует избегать ситуаций, когда (конец-начало)/шаг -- целое число, потому что в этом случае включение последнего элемента зависит от ошибок округления. Лучше, чтобы конец диапазона был где-то посредине шага.***

In [ ]:
a = np.arange(1, 16, 4)
b = np.arange(5., 21, 2)
c = np.arange(1, 10)
d = np.arange(5)
print(a)
print(b)
print(c)
print(d)

[ 1  5  9 13]
[ 5.  7.  9. 11. 13. 15. 17. 19.]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


***Последовательности чисел с постоянным шагом можно также создавать функцией `linspace`. Начало и конец диапазона включаются; последний аргумент -- число точек.***

In [ ]:
a = np.linspace(1, 15, 2)
b = np.linspace(5, 12, 10)
print(a)
print(b)

[ 1. 15.]
[ 5.          5.77777778  6.55555556  7.33333333  8.11111111  8.88888889
  9.66666667 10.44444444 11.22222222 12.        ]


**Задача 2:** создать и вывести последовательность чисел от 10 до 32 с постоянным шагом, длина последовательности -- 12. Чему равен шаг?

In [ ]:
# решение

a = np.linspace(10, 32, 12)
print(a)
print(a[1] - a[0])



[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
2.0


***Последовательность чисел с постоянным шагом по логарифмической шкале от $10^0$ до $10^3$.***

In [ ]:
b = np.logspace(0, 3, 12)
print(b)

[   1.            1.87381742    3.51119173    6.57933225   12.32846739
   23.101297     43.28761281   81.11308308  151.9911083   284.80358684
  533.66992312 1000.        ]


# 2. Операции над одномерными массивами.

***Все арифметические операции производятся поэлементно.***

In [ ]:
print(a)
print(b)

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]
[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]


In [ ]:
a = np.linspace(3, 33, 11)
b = np.linspace(-2, -22, 11)
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55.]
[  -6.  -24.  -54.  -96. -150. -216. -294. -384. -486. -600. -726.]
[-1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5]


***Один из операндов может быть скаляром, а не массивом.***

In [ ]:
print(5*a)
print(10 + b)

[ 15.  30.  45.  60.  75.  90. 105. 120. 135. 150. 165.]
[  8.   6.   4.   2.   0.  -2.  -4.  -6.  -8. -10. -12.]


In [ ]:
print((a + b) ** 2)
print(2 ** (a + b))

[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121.]
[2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01 6.400e+01 1.280e+02
 2.560e+02 5.120e+02 1.024e+03 2.048e+03]


***Если типы элементов разные, то идет каст к большему.***

In [ ]:
print(a + np.arange(11, dtype='int16'))
print(type(a[0]))

[ 3.  7. 11. 15. 19. 23. 27. 31. 35. 39. 43.]
<class 'numpy.float64'>


***В ``Numpy`` есть элементарные функции, которые тоже применяются к массивам поэлементно. Они называются универсальными функциями (``ufunc``).***

In [ ]:
type(np.cos)

numpy.ufunc

In [ ]:
np.cos(a)

array([-0.9899925 ,  0.96017029, -0.91113026,  0.84385396, -0.75968791,
        0.66031671, -0.54772926,  0.42417901, -0.29213881,  0.15425145,
       -0.01327675])

In [ ]:
np.log(b)

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

***Логические операции также производятся поэлементно.***

In [ ]:
print(a > b)
print(a == b)
print(a >= 10)

[ True  True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False False]
[False False False  True  True  True  True  True  True  True  True]


***Кванторы ``всеобщности`` и ``существования``.***
$$\forall$$
$$\exists$$

In [ ]:
c = np.arange(0., 20)
print(type(c[0]))

<class 'numpy.float64'>


In [ ]:
np.any(c == 0.), np.all(c)

(True, False)

***Inplace операции.***

In [ ]:
c += np.sin(4)
print(c)

[-0.7568025  0.2431975  1.2431975  2.2431975  3.2431975  4.2431975
  5.2431975  6.2431975  7.2431975  8.2431975  9.2431975 10.2431975
 11.2431975 12.2431975 13.2431975 14.2431975 15.2431975 16.2431975
 17.2431975 18.2431975]


***Inplace операции возможны только для операндов одинакового типа.***

In [ ]:
c *= 2
print(c)

[-1.51360499  0.48639501  2.48639501  4.48639501  6.48639501  8.48639501
 10.48639501 12.48639501 14.48639501 16.48639501 18.48639501 20.48639501
 22.48639501 24.48639501 26.48639501 28.48639501 30.48639501 32.48639501
 34.48639501 36.48639501]


In [ ]:
b = np.arange(1., 21, 1)

d = (b + c)
d /= b
print(d)

[-0.51360499  1.2431975   1.82879834  2.12159875  2.297279    2.41439917
  2.49805643  2.56079938  2.60959945  2.6486395   2.68058136  2.70719958
  2.72972269  2.74902821  2.76575967  2.78039969  2.79331735  2.80479972
  2.81507342  2.82431975]


***При делении ``ndarray`` на нули, исключения не бросается.***

In [ ]:
print(np.array([0.0, 0.0, 1.0, -1.0]) / np.array([1.0, 0.0, 0.0, 0.0]))

[  0.  nan  inf -inf]


***Могут понадобится константы.***

In [ ]:
print(np.e, np.pi)

2.718281828459045 3.141592653589793


In [ ]:
print(b)
print(b.cumsum())

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
[  1.   3.   6.  10.  15.  21.  28.  36.  45.  55.  66.  78.  91. 105.
 120. 136. 153. 171. 190. 210.]


***Посмотрим на сортировку numpy-массивов.***

In [ ]:
a = np.array([1, 5, 6, 10, -2, 0, 18])

In [ ]:
print(np.sort(a))
print(a)

[-2  0  1  5  6 10 18]
[ 1  5  6 10 -2  0 18]


***Теперь попробуем как метод.***

In [ ]:
a.sort()
print(a)

[-2  0  1  5  6 10 18]


In [ ]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

***Объединим массивы.***

In [ ]:
c = np.hstack((a, b, 5*b))
c

array([-2.,  0.,  1.,  5.,  6., 10., 18.,  1.,  1.,  1.,  1.,  1.,  5.,
        5.,  5.,  5.,  5.])

***Расщепление массива.***

In [ ]:
x1, x2, x3, x4 = np.hsplit(a, [3, 5, 6])
print(a)
print(x1)
print(x2)
print(x3)
print(x4)

[-2  0  1  5  6 10 18]
[-2  0  1]
[5 6]
[10]
[18]


***Функции ``append`` ``delete`` ``insert`` не Inplace функции.***

In [ ]:
print(np.delete(a, [2, 4, 1]))
print(a)

[-2  5 10 18]
[-2  0  1  5  6 10 18]


In [ ]:
np.insert(a, 2, [-1, -1])

array([-2,  0, -1, -1,  1,  5,  6, 10, 18])

In [ ]:
np.append(a, [2.2, 2.1])

array([-2. ,  0. ,  1. ,  5. ,  6. , 10. , 18. ,  2.2,  2.1])

## Индексирование массивов и срезы

***Массив в обратном порядоке.***

In [ ]:
a[::-1]

array([18, 10,  6,  5,  1,  0, -2])

***Диапазон индексов. Создаётся новый заголовок массива, указывающий на те же данные. Изменения, сделанные через такой массив, видны и в исходном массиве.***

In [ ]:
print(a)

[-2  0  1  5  6 10 18]


In [ ]:
a[2:5]

array([1, 5, 6])

In [ ]:
b = a[0:6] # копия не создается
b[1] = -1000
print(a)

[   -2 -1000     1     5     6    10    18]


***Диапозоны с шагами.***

In [ ]:
b = a[0:4:2]
print(b)

# подмассиву можно присваивать скаляр
a[1:6:3] = 0
print(a)

[-2  1]
[-2  0  1  5  0 10 18]


***Чтобы скопировать и данные массива, нужно использовать метод ``copy``.***

In [ ]:
b = a.copy()
b[2] = -4
print(b)
print(a)

[-2  0 -4  5  0 10 18]
[-2  0  1  5  0 10 18]


In [ ]:
print(a[[5,3,1]]) # массив индексов

[10  5  0]


**Задание 3:**  
- Создать массив чисел от $-4\pi$  до $4\pi $, количество точек 100
- Посчитать сумму поэлементных квадратов синуса и косинуса для данного массива  
- С помощью ``np.all`` проверить, что все элементы равны единице.

In [ ]:
# решение

x = np.linspace(-4*np.pi, 4*np.pi, 100)

np.all((np.sin(x)**2 + np.cos(x)**2).round() == 1)

True

# 3. Двумерные массивы

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
a.ndim, a.shape, len(a), a.size

(2, (2, 2), 2, 4)

***Обращение по индексу.***

In [ ]:
a[1][1], a[1,1]

(4, 4)

***Атрибуту ``shape`` можно присвоить новое значение -- кортеж размеров по всем координатам. Получится новый заголовок массива; его данные не изменятся.***

In [ ]:
b = np.arange(0, 20)
b.shape = (2, 10)
print(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [ ]:
print(b.ravel()) # стягивание в одномерный массив

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
a = np.ones((3, 3)) # подать tuple
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
b = np.zeros((3, 4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
c = np.eye(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
d = np.diag(np.array([1, 2, 3, 4]))
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


***Задание 4:***
Создать квадратную матрицу размера 8, на главной диаг. арифметическая прогрессия с шагом 3 (начиная с 3), а на побочной -1, остальные элементы 0.

In [ ]:
# решение

a = -1*np.eye(8)[::-1] + np.diag(np.arange(3, 27, 3))
print(a)


[[ 3.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  6.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  9.  0.  0. -1.  0.  0.]
 [ 0.  0.  0. 12. -1.  0.  0.  0.]
 [ 0.  0.  0. -1. 15.  0.  0.  0.]
 [ 0.  0. -1.  0.  0. 18.  0.  0.]
 [ 0. -1.  0.  0.  0.  0. 21.  0.]
 [-1.  0.  0.  0.  0.  0.  0. 24.]]


***Умножение матриц.***

In [ ]:
a = 5*np.ones((5, 5))
b = np.eye(5) + 1
print(a, '\n')
print(b)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]] 

[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [ ]:
print(a*b, '\n') # поэлементное умножение
print(a @ b, '\n') # матричное умножение
print(a.dot(b)) 

[[10.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 10.  5.  5.]
 [ 5.  5.  5. 10.  5.]
 [ 5.  5.  5.  5. 10.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]


***Двумерные массивы, зависящие только от одного индекса: $x_{ij}=u_j$, $y_{ij}=v_i$***

In [ ]:
u = np.linspace(1, 2, 2)
v = np.linspace(4, 8, 3)
print(u)
print(v)

[1. 2.]
[4. 6. 8.]


In [ ]:
x, y = np.meshgrid(u, v)
print(x, '\n')
print(y)

[[1. 2.]
 [1. 2.]
 [1. 2.]] 

[[4. 4.]
 [6. 6.]
 [8. 8.]]


In [ ]:
print(x.reshape(6)) # то же самое, что и shape

[1. 2. 1. 2. 1. 2.]


***Задание 5:***
- Отобразить вектор размера 100, в котором вычеркивается **x**, если **x** --- составное (т. е. не является простым)

In [ ]:
is_prime = np.ones(100, dtype=bool)

In [ ]:
is_prime[:2] = False

In [ ]:
N_max = int(np.sqrt(len(is_prime)))
for i in range(2, N_max):
    is_prime[2*i::i] = False # начинаем с 2i с шагом i
    
print(is_prime)

[False False  True  True False  True False  True False False False  True
 False  True False False False  True False  True False False False  True
 False False False False False  True False  True False False False False
 False  True False False False  True False  True False False False  True
 False False False False False  True False False False False False  True
 False  True False False False False False  True False False False  True
 False  True False False False False False  True False False False  True
 False False False False False  True False False False False False False
 False  True False False]


In [ ]:
print(is_prime[17])
print(is_prime[25])

True
False


***Маски.***

In [ ]:
a = np.arange(20)
print(a % 3 == 0)
print(a[a % 3 == 0])

[ True False False  True False False  True False False  True False False
  True False False  True False False  True False]
[ 0  3  6  9 12 15 18]


***След (trace) - сумма диагональных элементов.***

In [ ]:
b = np.diag(a[a >= 10])
print(b)
print(np.trace(b))

[[10  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0]
 [ 0  0  0 13  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0]
 [ 0  0  0  0  0  0  0 17  0  0]
 [ 0  0  0  0  0  0  0  0 18  0]
 [ 0  0  0  0  0  0  0  0  0 19]]
145


# 4. Тензоры (многомерные массивы)

In [ ]:
X = np.arange(64).reshape(8, 2, 4)
print(X)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]]

 [[56 57 58 59]
  [60 61 62 63]]]


In [ ]:
X.shape, len(X), X.size, X.ndim

((8, 2, 4), 8, 64, 3)

***Посмотрим на суммы по разным осям.***

In [ ]:
print(np.sum(X, axis=0), '\n')
print(np.sum(X, axis=1), '\n')
print(np.sum(X, axis=2), '\n')

# суммируем сразу по двум осям, то есть для фиксированной i 
# суммируем только элементы с индексами (i, *, *)
print(np.sum(X, axis=(1, 2)))

[[224 232 240 248]
 [256 264 272 280]] 

[[  4   6   8  10]
 [ 20  22  24  26]
 [ 36  38  40  42]
 [ 52  54  56  58]
 [ 68  70  72  74]
 [ 84  86  88  90]
 [100 102 104 106]
 [116 118 120 122]] 

[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]
 [134 150]
 [166 182]
 [198 214]
 [230 246]] 

[ 28  92 156 220 284 348 412 476]


# 5. Линейная алгебра

In [ ]:
a = np.array([[2, 1], [2, 3]])
print(a)

[[2 1]
 [2 3]]


***Определитель.***

In [ ]:
np.linalg.det(a)

4.0

***Нахождениия обратной.***

In [ ]:
b = np.linalg.inv(a)
print(b)

[[ 0.75 -0.25]
 [-0.5   0.5 ]]


In [ ]:
print(a.dot(b))
print(b.dot(a))

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [ ]:
c = np.array([[2, 1], [6, 3]])
print(c)
print(np.linalg.det(c))

[[2 1]
 [6 3]]
0.0


In [ ]:
np.linalg.inv(c)

LinAlgError: ignored

***Решение НЛУ.***
$$ A \cdot x = v $$

In [ ]:
v = np.array([5, -10])
print(np.linalg.solve(a, v))
print(b.dot(v))

[ 6.25 -7.5 ]
[ 6.25 -7.5 ]


***Найдем собственные вектора матрицы A.***
$$ A \cdot x = \lambda \cdot x $$

In [ ]:
l, u = np.linalg.eig(a)
print(l)
print(u)

[1. 4.]
[[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]


***Собственные значения матриц A и A.T совпадают.***

In [ ]:
l, u = np.linalg.eig(a.T)
print(l)
print(u)

[1. 4.]
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [ ]:
l, u = np.linalg.eig(np.eye(3))
print(l)
print(u)

[1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


***Производительность.***

In [ ]:
%%time

sum_value = np.sum(np.arange(10**7))
print(sum_value)

49999995000000
CPU times: user 85 ms, sys: 17 ms, total: 102 ms
Wall time: 105 ms


In [ ]:
%%time
arr = 5*np.arange(10**7)

CPU times: user 27.2 ms, sys: 0 ns, total: 27.2 ms
Wall time: 28.3 ms


# Полезные ссылки

[Введение в Анализ Данных](https://mipt-stats.gitlab.io/jekyll/update/2020/02/01/ad.html)

[GitHub NumPy](https://github.com/numpy/numpy)

[Документация по NumPy](https://numpy.org/doc/stable/)

[mlcource.ai](https://mlcourse.ai)